public enum BackPackClassColumn
{
	BACKPACK_STYLE = 0,
	BACKPACK_CLASS = 1,
	BACKPACK_BAG_CAPACITY = 2,
	BACKPACK_FORMULA_PARAMETER_1 = 3,
	BACKPACK_FORMULA_PARAMETER_2 = 4,
	BACKPACK_COLUMN_COUNT = 5
}
