public enum BuffTableColumn
{
	BUFF_TABLE_ID = 0,
	BUFF_TABLE_LEVEL = 1,
	BUFF_TABLE_NAME = 2,
	BUFF_TABLE_TYPE = 3,
	BUFF_TABLE_FUNC1 = 4,
	BUFF_TABLE_X1 = 5,
	BUFF_TABLE_Y1 = 6,
	BUFF_TABLE_FUNC2 = 7,
	BUFF_TABLE_X2 = 8,
	BUFF_TABLE_Y2 = 9,
	BUFF_TABLE_FUNC3 = 10,
	BUFF_TABLE_X3 = 11,
	BUFF_TABLE_Y3 = 12,
	BUFF_TABLE_ICON = 13,
	BUFF_TABLE_RESOURCE = 14,
	BUFF_TABLE_DESCRIPTION1 = 15,
	BUFF_TABLE_DESCRIPTION2 = 16,
	BUFF_TABLE_COLUMN_COUNT = 17
}
