public enum EffectPoolType
{
	HIT_BLOOD = 0,
	BULLET_WALL_SPARK = 1,
	BULLET_FLOOR_SPARK = 2,
	SHOTGUN_WALL_SPARK = 3,
	SHOTGUN_FLOOR_SPARK = 4,
	BULLET_TRAIL = 5,
	BULLET_TRAIL_FPS = 6,
	RIFLE_SPARK = 7,
	SHOTGUN_SPARK = 8,
	SHOTGUN_SPARK_T = 9,
	FIRE_BULLET_TRAIL = 10,
	SHOCK_BULLET_TRAIL = 11,
	CORROSIVE_BULLET_TRAIL = 12,
	FIRE_BULLET_SPARK = 13,
	SHOCK_BULLET_SPARK = 14,
	CORROSIVE_BULLET_SPARK = 15,
	UN_LOOP_WEAPON_SPARK = 16,
	UN_LOOP_WEAPON_FIRE_SPARK = 17,
	UN_LOOP_WEAPON_SHOCK_SPARK = 18,
	UN_LOOP_WEAPON_CORROSIVE_SPARK = 19,
	NUM = 20
}
