public enum ItemTypes
{
	ITEM_TYPE_WEAPON = 0,
	ITEM_TYPE_WEAPON_G = 1,
	ITEM_TYPE_SHIELD = 2,
	ITEM_TYPE_SLOT = 3,
	ITEM_TYPE_PILL = 4,
	ITEM_TYPE_MONEY = 5,
	ITEM_TYPE_BACKPACK = 6,
	ITEM_TYPE_STORY_ITEM = 7,
	ITEM_TYPE_BULLET = 8,
	ITEM_TYPE_FIRST_AID = 9
}
