public enum NameTableColumn
{
	NAME_TABLE_ITEM_NAME = 0,
	NAME_TABLE_ITEM_STYLE = 1,
	NAME_TABLE_LEVEL_FLOOR_LIMIT = 2,
	NAME_TABLE_LEVEL_UPPER_LIMIT = 3,
	NAME_TABLE_ITEM_TYPE = 4,
	NAME_TABLE_SPECIAL_ID_FOR_PILL = 5,
	NAME_TABLE_COLUMN_COUNT = 6
}
