public enum PillClassColumn
{
	PILL_STYLE = 0,
	PILL_CLASS = 1,
	PILL_HP_RECOVERY = 2,
	PILL_HP_SUPERPOSITION = 3,
	PILL_FORMULA_PARAMETER_1 = 4,
	PILL_FORMULA_PARAMETER_2 = 5,
	PILL_COLUMN_COUNT = 6
}
