public enum ShieldClassColumn
{
	SHIELD_STYLE = 0,
	SHIELD_CLASS = 1,
	SHIELD_BASE_CAPACITY = 2,
	SHIELD_RECOVERY_SPEED = 3,
	SHIELD_RECOVERY_DELAY = 4,
	SHIELD_FORMULA_PARAMETER_1 = 5,
	SHIELD_FORMULA_PARAMETER_2 = 6,
	SHIELD_FIXED_SKILL_PROPERTY_1 = 7,
	SHIELD_FIXED_SKILL_PROPERTY_2 = 8,
	SHIELD_FIXED_SKILL_PROPERTY_3 = 9,
	SHIELD_FIXED_SKILL_PROPERTY_4 = 10,
	SHIELD_COLUMN_COUNT = 11
}
