public enum SkillColumn
{
	SKILL_COLUMN_PROPERTY_NAME = 0,
	SKILL_COLUMN_PROPERTY_VALUE = 1,
	SKILL_COLUMN_DESCRIPTION = 2,
	SKILL_COLUMN_SCORE = 3,
	SKILL_COLUMN_PARAMETER_1 = 4,
	SKILL_COLUMN_PARAMETER_2 = 5,
	SKILL_COLUMN_COLOR = 6,
	SKILL_CONFLICT_GROUP = 7,
	SKILL_COLUMN_COUNT = 8
}
