public enum SlotClassColumn
{
	SLOT_STYLE = 0,
	SLOT_CLASS = 1,
	SLOT_SKILL_CAPACITY = 2,
	SLOT_FORMULA_PARAMETER_1 = 3,
	SLOT_FORMULA_PARAMETER_2 = 4,
	SLOT_FIXED_SKILL_PROPERTY_1 = 5,
	SLOT_FIXED_SKILL_PROPERTY_2 = 6,
	SLOT_FIXED_SKILL_PROPERTY_3 = 7,
	SLOT_FIXED_SKILL_PROPERTY_4 = 8,
	SLOT_COLUMN_COUNT = 9
}
