public enum SpecialClassColumn
{
	SPECIAL_ID = 0,
	SPECIAL_CALL_NAME = 1,
	SPECIAL_DISPLAY_NAME = 2,
	SPECIAL_CLASS = 3,
	SPECIAL_TYPE = 4,
	SPECIAL_NUMBER = 5,
	SPECIAL_QUALITY = 6,
	SPECIAL_DESCRIPTION = 7,
	SPECIAL_ICON = 8,
	SPECIAL_PREVIEW_ICON = 9,
	SPECIAL_PREFAB_NAME = 10,
	SPECIAL_COUNT = 11
}
