public enum WeaponSkillClass
{
	WEAPON_SKILL_ALLOW_SUBMACHINE_GUN = 7,
	WEAPON_SKILL_ALLOW_ASSAULT_RIFLE = 8,
	WEAPON_SKILL_ALLOW_PISTOL = 9,
	WEAPON_SKILL_ALLOW_REVOLVER = 10,
	WEAPON_SKILL_ALLOW_SHOTGUN = 11,
	WEAPON_SKILL_ALLOW_SNIPER = 12,
	WEAPON_SKILL_ALLOW_RPG = 13,
	WEAPON_SKILL_ALLOW_GRENADE = 14,
	WEAPON_SKILL_ALLOW_COUNT = 15
}
